<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>囧途网—骑行导航，骑行路线</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="`$url~/img/fav.jpg"> 
    <link href="`$url~/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="`$url~/css/bootstrap-theme.min.css" rel="stylesheet" media="screen">
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <p>连接成功，正在跳转中。。。<p/>
    <script>
      var isreg="`$isreg~";
      var pwindow=window.opener;
      pwindow.location.href="http://www.joneto.com";
      setTimeout(function(){
        window.close();
      },1000);
      
    </script>
  </body>
</html>