`include file=index/header.phtml~
<script type="text/javascript" charset="utf-8" src="`$url~/js/ueditor/ueditor.config.js"></script>
<script type="text/javascript" charset="utf-8" src="`$url~/js/ueditor/ueditor.all.min.js"> </script>
<script type="text/javascript" charset="utf-8" src="$url~/js/ueditor/lang/zh-cn/zh-cn.js"></script>
<div class="container" style="margin-top:30px;">
	<div class="row">
		`include file=index/ucmenu.phtml~
		<div class="col-md-9 jt-uc-container">


      <ul id="myTab" class="nav nav-tabs">
        <li class="active"><a href="`$url~/travel" >游记管理</a></li>
        
      </ul>
      <div id="myTabContent" class="tab-content" style="padding:10px;height:100%;">
        <div class="tab-pane fade active in" id="home" style="position:relative">
          <div style="position:absolute;right:20px;top:0px;">`$page_str~</div>
          <div style="height:500px;" id="line-map">
            <p>
              <script id="travel-editor" type="text/plain" style="width:100%;height:500px;"></script>
            </p>
          </div>

        </div>
        
      </div>
    

		</div>
	</div>

</div>
<script>
UE.getEditor('travel-editor');
</script>
`include file=index/footer.phtml~