`include file=index/header.phtml~
<div class="container" style="margin-top:30px;">
	<div class="row">
		`include file=index/ucmenu.phtml~
		<div class="col-md-9 jt-uc-container">


      <ul id="myTab" class="nav nav-tabs">
        <li class="active"><a href="`$url~/travel" >游记管理</a></li>
        
      </ul>
      <div id="myTabContent" class="tab-content" style="padding:10px;height:100%;">
        <div class="tab-pane fade active in" id="home" style="position:relative">
          <div style="position:absolute;right:20px;top:0px;">`$page_str~</div>
          <div style="height:500px;" id="line-map">
            <p><a class="btn btn-default" id="line-add" target="_self" href="`$url~/travel/add"><span class="glyphicon glyphicon-plus"></span>新增游记</a></p>
            <p>
            <table class="table" id="pictures">
               <tr>
                <th width="40%">
                  标题
                </th>
                 <th width="20%">
                  路书
                </th>
                <th width="20%">
                  创建时间
                </th>
                <th>
                  操作
                </th>
              </tr>
              `foreach from=$arts item=art~
              <tr>
                <td width="40%">
                  <p><a href="`$img.img_big~" target="_blank">`$art.title~</a></p>
                </td>
                <td width="20%">
                  <p><a href="`$url~/material/editline/id/`$art.line_id~" target="_blank">`$art.name~</a></p>
                </td>
                <td width="20%">
                  `$art.add_time|date_format:'%Y-%m-%d %H:%M'~
                </td>
                <td>
                    <a href="`$url~/travel/edit/id/`$art.id~" class="text-muted" data-id="`$art.id~" target="_self"><span class="glyphicon glyphicon-edit"></span>编辑</a>&nbsp;&nbsp;
                    <a href="javascript:void(0);" class="text-muted" id="delart" data-id="`$art.id~"><span class="glyphicon glyphicon-trash"></span>删除</a>&nbsp;&nbsp;
                  
                </td>
              </tr>
              `/foreach~
            </table>
          </p>
          </div>

        </div>
        
      </div>
    

		</div>
	</div>

</div>
<script>
$(document).ready(function(){
  $("#delart").click(function(){
    var id=$(this).attr("data-id");
    if(!confirm("确定要删除游记么？")) return false;
    $.get(site_url+"/travel/delete/id/"+id,function(rs){
      //window.location.reload();
    });
  });
});
</script>
`include file=index/footer.phtml~