<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>囧途网—囧途中的囧图集,囧文集,旅途百科,驴友集散地</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="img/fav.jpg"> 
    <link href="`$url~/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="`$url~/css/bootstrap-theme.min.css" rel="stylesheet" media="screen">
    <link href="`$url~/css/line.css" rel="stylesheet" media="screen">
    <script src="`$url~/js/jquery.js"></script>
    <script src="http://api.map.baidu.com/api?v=2.0&ak=FDd8e975a4304939cfe447098f4594cc"></script>
    <script>
      var site_url="`$url~";
      var curl_point='`$point~';
      curl_point=eval("("+curl_point+")");
    </script>
    <!--[if lt IE 9]>
      <script src="`$url~/js/html5shiv.js"></script>
      <script src="`$url~/js/respond.min.js"></script>
    <![endif]-->
  </head>
  <body onbeforeunload="event.returnValue=myexit()">
    <div class="line-wrap clearfix">
      <div class="line-top">
        <div style="padding:20px 0 0 100px;float:left;"><img src="`$url~/img/logo.png"></div>
        <div style="margin-left:350px;padding:30px 0 0 200px;">
          <button class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-eye-open">预览</span></button>
          <button class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-ok-sign">保存路书</span></button>
        </div>
      </div>
      <div class="line-left panel panel-default">
        <div class="panel-heading"><span class="text-info"><span class="glyphicon glyphicon-pencil"></span>填写路书基本信息</span></div>
        <div class="panel-body">
          <div style="padding:0 15px;">
          <form class="form-horizontal" role="form">
            <div class="form-group">
              <label for="line-name" class="control-label">名称:<span class="text-muted">（如：清明湖州到杭州）</span></label>
              <input type="email" class="form-control" id="line-name" placeholder="名称">
            </div>
            <div class="form-group">
              <label for="line-start" class="control-label">起点:</label>
              <input type="text" class="form-control place-name" id="line-start" placeholder="起点">
            </div>
            
              <div class="col-sm-offset-7 col-sm-5"><a href="javascript:void(0);"><span class="glyphicon glyphicon-plus-sign add-bar"></span>新增途经点</a></div>
              
 
            <div class="form-group">
              <label for="line-end" class="control-label">终点:</label>
              <input type="text" class="form-control place-name" id="line-end" placeholder="终点">
            </div>
    
            <div class="form-group">
              <div class="col-sm-offset-9 col-sm-3">
                <button type="submit" class="btn btn-primary">创建</button>
              </div>
            </div>
          </form>
          </div>


        </div>
      </div>

      <div class="line-main panel panel-default">
        <div id="line-map" style="height:100%;"></div>
      </div>
    </div>
  

    
    <script src="`$url~/js/bootstrap.min.js"></script>
    <script src="`$url~/js/line.js" type="text/javascript"></script>
    <script>
      
    var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
    document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F4c42ddf892cc186c28070d3ae395e0d9' type='text/javascript'%3E%3C/script%3E"));
    </script>

  </body>
</html>