`include file=index/header.phtml~
<div class="container" style="margin-top:30px;">
	<div class="row">
		`include file=index/ucmenu.phtml~
		<div class="col-md-9 jt-uc-container">


      <ul id="myTab" class="nav nav-tabs">
        <li class="active"><a href="#home" data-toggle="tab">图片</a></li>
        <li class=""><a href="#profile" data-toggle="tab">地图</a></li>
        
      </ul>
      <div id="myTabContent" class="tab-content" style="padding:10px;height:100%;">
        <div class="tab-pane fade active in" id="home" style="position:relative">
          <div id="container">
          </div><em class="text-muted" style="position:absolute;left:50px;top:5px;">大小: 不超过2M,    格式:  png, jpeg, jpg, gif</em>

          <div style="position:absolute;right:20px;top:0px;">`$page_str~</div>

          <p>
            <table class="table" id="pictures">
              `foreach from=$imgs item=img~
              <tr>
                <td width="50%">
                  <p><h4>`$img.img_name~</h4></p>
                  <p><a href="`$img.img_big~" target="_blank"><img src="`$img.img_big~" style="height:80px;width:80px;"/></a></p>
                </td>

                <td width="25%">
                  <h4>`$img.size~<em class="text-muted">bytes</em></h4>
                </td>
                <td>
                  <h4 class="text-center" id="pic-op" style="display:none;">
                    <a href="/material/saveimg/id/`$img.id~" class="text-muted" target="_blank"><span class="glyphicon glyphicon-save"></span></a>&nbsp;&nbsp;
                    <a href="javascript:void(0);" class="text-muted" id="delimg" data-id="`$img.id~"><span class="glyphicon glyphicon-trash"></span></a>&nbsp;&nbsp;
                  </h4>
                </td>
              </tr>
              `/foreach~
            </table>
          </p>
          <hr>
          <div style="position:relative;"><div style="position:absolute;right:20px;top:0px;">`$page_str~</div></div>
        </div>
        <div class="tab-pane fade" id="profile">
          <p>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid. Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four loko farm-to-table craft beer twee. Qui photo booth letterpress, commodo enim craft beer mlkshk aliquip jean shorts ullamco ad vinyl cillum PBR. Homo nostrud organic, assumenda labore aesthetic magna delectus mollit. Keytar helvetica VHS salvia yr, vero magna velit sapiente labore stumptown. Vegan fanny pack odio cillum wes anderson 8-bit, sustainable jean shorts beard ut DIY ethical culpa terry richardson biodiesel. Art party scenester stumptown, tumblr butcher vero sint qui sapiente accusamus tattooed echo park.</p>
        </div>
      </div>
    

		</div>
	</div>

</div>
<div style="display:none">
<input type="hidden" id="joneto" value="`$jt~">
</div>
`include file=index/footer.phtml~