`include file=index/header.phtml~
<div class="container" style="margin-top:30px;">
	<div class="row">
		`include file=index/ucmenu.phtml~
		<div class="col-md-9 jt-uc-container">


      <ul id="myTab" class="nav nav-tabs">
        <li class="active"><a href="/material" >图片</a></li>
        <li class=""><a href="/material/map">路书</a></li>
        
      </ul>
      <div id="myTabContent" class="tab-content" style="padding:10px;height:100%;">
        <div class="tab-pane fade active in" id="home" style="position:relative">
          <div id="container">
          </div><em class="text-muted" style="position:absolute;left:50px;top:5px;">大小: 不超过2M,    格式:  png, jpeg, jpg, gif</em>

          <div style="position:absolute;right:20px;top:0px;">`$page_str~</div>

          <p>
            <table class="table" id="pictures">
              `foreach from=$imgs item=img~
              <tr>
                <td width="50%">
                  <p><h4>`$img.img_name~</h4></p>
                  <p><a href="`$img.img_big~" target="_blank"><img src="`$img.img_big~" style="height:80px;width:80px;"/></a></p>
                </td>

                <td width="25%">
                  <h4>`$img.size~<em class="text-muted">bytes</em></h4>
                </td>
                <td>
                  <h4 class="text-center" id="pic-op" style="display:none;">
                    <a href="/material/saveimg/id/`$img.id~" class="text-muted" target="_blank"><span class="glyphicon glyphicon-save"></span></a>&nbsp;&nbsp;
                    <a href="javascript:void(0);" class="text-muted" id="delimg" data-id="`$img.id~"><span class="glyphicon glyphicon-trash"></span></a>&nbsp;&nbsp;
                  </h4>
                </td>
              </tr>
              `/foreach~
            </table>
          </p>
          <hr>
          <div style="position:relative;"><div style="position:absolute;right:20px;top:0px;">`$page_str~</div></div>
        </div>
        
      </div>
    

		</div>
	</div>

</div>
<div style="display:none">
<input type="hidden" id="joneto" value="`$jt~">
</div>
<script src="`$url~/js/uploadify/jquery.uploadify.min.js"></script>
<script>
$(document).ready(function(){
  setTimeout(function () {
      $('.bs-top').affix()
    }, 100)

    $("#container").uploadify({
      height        : 30,
      swf           : 'http://www.joneto.com/js/uploadify/uploadify.swf',
      uploader      : 'http://www.joneto.com/material/upload',
      width         : 50,
      buttonText    : "上传",
      formData    : {"jt_id":$("#joneto").val()},
      onQueueComplete:function(data){
        window.location.reload();
      }
    });

    $("#pictures tr").hover(
      function(){
        $(this).css({"background":"#f5f5f5"}).find("#pic-op").show();
      },
      function(){
        $(this).css({"background":"#ffffff"}).find("#pic-op").hide();
      }

    );

    $("#delimg").click(function(){
      var id=$(this).attr("data-id");
      $.get("/material/delimg/id/"+id,function(){
        window.location.reload();
      });
    });
});
</script>
`include file=index/footer.phtml~