`include file=index/header.phtml~
<div class="container" style="margin-top:30px;">
	<div class="row">
		`include file=index/ucmenu.phtml~
		<div class="col-md-9 jt-uc-container">


      <ul id="myTab" class="nav nav-tabs">
        <li class=""><a href="`$url~/material" >图片</a></li>
        <li class="active"><a href="`$url~/material/map">路书</a></li>
        
      </ul>
      <div id="myTabContent" class="tab-content" style="padding:10px;height:100%;">
        <div class="tab-pane fade active in" id="home" style="position:relative">
          <div style="height:500px;" id="line-map">
            <p><button class="btn btn-default" id="line-add"><span class="glyphicon glyphicon-plus"></span>新增路线</button></p>
            <hr/>
          </div>

        </div>
        
      </div>
    

		</div>
	</div>

</div>
<script src="`$url~/js/map.js"></script>
`include file=index/footer.phtml~