<div class="col-xs-12">
  <form class="jt-form" role="form">
    <div class="form-group clearfix">
      <label for="username" class="jt-label-normal">用户名：</label>
        <input type="text" ng-pattern="word" class="form-control" id="username" name="jone" placeholder="用户名或邮箱..." required/>
      
    </div>

   <div class="form-group clearfix">
      <label for="password" class="jt-label-normal">密码：</label><a class="pull-right text-muted" href="#/getpass"><small>忘记登录密码</small></a>
        <input type="password" class="form-control" id="password" name="to" placeholder="请输入密码..." required/>
      
    </div>

     <button type="submit" class="btn btn-warning" style="width:100%;">登录</button>

  </from>
</div>