<div class="col-xs-12">
  <form class="jt-form" role="form" name="regform">
    <div class="form-group clearfix">
      <label for="email" class="jt-label-normal">邮箱：</label>
        <input type="email" class="form-control" id="email" name="jone" placeholder="请输入邮箱..." required/>
      
    </div>

   <div class="form-group clearfix">
      <label for="password" class="jt-label-normal">密码：</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="请输入密码..." required/>

    </div>

     <button type="submit" class="btn btn-warning" style="width:100%;">注册</button>

  </from>
</div>