`include file=index/header.phtml~
    <!--内容-->
    <div class="container" style="margin-top:40px;">
      <div class="row">
        <div class="col-md-8">

          <div class="row">
              <div class="col-md-10">
                  <p class="text-muted"><span class="glyphicon glyphicon-list-alt"></span> <b>&nbsp;最新动态</b></p>
              </div>
              <div class="col-md-2">
                <p class="text-muted text-right"><span class="glyphicon glyphicon-cog"></span>&nbsp;<small>设置</small></p>
              </div>
          </div>
          
          `foreach from=$arts item=art~
          <div class="row jt-mt-10 jt-bt-1">
            <div class="col-md-12 clearfix jt-mt-10">
     
                <div class="pull-left jt-wt-40">
                  <a href="/people/so898" class="pull-left"><img src="`$art.avatar~" alt="" class="jt-avatar-40 img-rounded"></a>
                  <button type="button" class="btn btn-xs jt-mt-10 btn-info" title="赞">&nbsp;&nbsp;`$art.like~&nbsp;&nbsp;</button>
                </div>
                <div class="jt-ml-48">
                  <div>
                    <div class="text-muted">
                      <a href="/people/so898" class="text-muted"><small>`$art.user_name~</small></a>*<a href="#" class="text-muted"><small>关注TA</small></a>
                      <span class="pull-right text-muted">精选内容</span>
                    </div>
                    <p><a href="`$url~/index/note/id/`$art.id~" target="_blank"><strong>`$art.title~</strong></a></p>
                    <p class="content-descript clearfix">
                      `if $art.imgs~
                      <img src="`$art.imgs|img~" class="content-img">
                      `/if~
                      `$art.descript~… <a href="javascript:void(0);" target="_blank" class="show-all">显示全部</a>
                      <textarea class="content hidden">`$art.content~</textarea>
                      
                    </p>
                  </div>
                  <div>
                    <a class="text-muted" href="#"><span class="glyphicon glyphicon-plus"></span>&nbsp;收藏路线</a>

                    <a class="text-muted jt-ml-10" href="#"><span class="glyphicon glyphicon-comment"></span>&nbsp;共`$art.comment~条评论</a>

                    <a class="content-handup text-muted jt-ml-10 pull-right hide" href="javascript:void(0);"><span class="glyphicon glyphicon-open"></span>&nbsp;收起</a>
                  </div>
                </div>
            </div>
            

          </div>
          `/foreach~
        </div>

        <div class="col-md-4">
          <ul class="nav nav-pills nav-stacked">
            <li><a href="#" class="text-muted"><span class="glyphicon glyphicon-file"></span>&nbsp;我的草稿</a></li>
            <li><a href="#" class="text-muted"><span class="glyphicon glyphicon-bookmark"></span>&nbsp;我的收藏</a></li>
            <li><a href="#" class="text-muted"><span class="glyphicon glyphicon-check"></span>&nbsp;我关注的人</a></li>
            <li><a href="#" class="text-muted"><span class="glyphicon glyphicon-tower"></span>&nbsp;邀请好友加入囧途</a></li>
          </ul>
          <hr>
          <p class="jt-pl-10"><b>你可能感兴趣的人</b></p>
          <div class="clearfix">
            <div class="pull-left">
              <a href="#">
                <img  class="jt-avatar-25" src="http://p2.zhimg.com/0e/b5/0eb52fe6f_m.jpg"/>
              </a>
            </div>
            <div class="jt-ml-45">
              <p><a href="#"><small>李双龙</small></a></p>
              <p class="text-muted">产品经理，从事教育类互联网产品研发</p>
              <p class="text-muted">他也关注 互联网 • 关注</p>
            </div>
          </div>

          <hr>
          <p class="jt-pl-10"><b>囧途提示</b></p>

          <div class="clearfix">
            <div class="jt-ml-10">
              
              <p class="text-muted">&nbsp;&nbsp;&nbsp;&nbsp;出行都是为了获得一段美好的体验，带上一副好心情traveling light,既然是traveling light,就一定要轻，带上足够的银子，几件换洗的衣服，就果断出发吧，千万别上山背石头哦。。。</p>
            </div>
            
          </div>

          <hr>
          <p class="jt-pl-10"><b>赞助商</b></p>

          <div class="clearfix">
            <div class="jt-ml-10">
              
              <p class="text-muted"><a href="http://s.click.taobao.com/t?e=m%3D2%26s%3DEOjMP%2FZdglccQipKwQzePCperVdZeJviEViQ0P1Vf2kguMN8XjClAhaeD7ZFp2KhmCBgKg63Ff9YU0kl1dGVYgbAqy1VXNRYqgOH9%2Fz8vrH6G2ObSgSB3%2Bdn1BbglxZYxUhy8exlzcq9AmARIwX9K%2BnbtOD3UdznPV1H2z0iQv%2FtmSjxrhnChg%3D%3D" target="_blank"><img src="http://gtms01.alicdn.com/tps/i1/T1vEJoFrFbXXcg0_ET-336-280.jpg" /></a></iframe></p>
            </div>
            
          </div>
        </div>
      </div>


    </div>
    <!--底部-->
`include file=index/footer.phtml~