`include file=index/header.phtml~
    <!--内容-->
    <div class="container" style="margin-top:70px;">
      <div class="row">
        <div class="col-md-8">

          <div class="row">
              <div class="col-md-10">
                  <p class="text-muted"><span class="glyphicon glyphicon-list-alt"></span> <b>&nbsp;最新动态</b></p>
              </div>
              <div class="col-md-2">
                <p class="text-muted"><span class="glyphicon glyphicon-cog"></span>&nbsp;<small>设置</small></p>
              </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="jt-bt">
                <p class="text-muted pager">你的首页暂时还没有内容，多关注些人吧 <a href="#">换一批</a>·<a href="#">更多推荐</a></p>
                <table class="table table-bordered">
                  <tr>
                    <td width="33.3%">
                      <div class="suggest-item-inner">
                        <div class="row">
                          <div class="col-md-12">
                            <a href="/people/so898" class="pull-left"><img src="http://p2.zhimg.com/0e/b5/0eb52fe6f_m.jpg" alt="" class="jt-avatar-40 img-rounded"></a>
                            <div class="pull-left jt-ml-10">
                              <a href="/people/so898" class="item-link">Bill Cheng</a>
                              <p class="text-muted">517 个回答</p>
                            </div>
                          </div>
                        </div>
                        
                        <div class="text-muted jt-details">
                          <small>是一只死掉的考拉，大家不用在意</small>
                        </div>
                        <hr class="devider hr-medium">
                        <div class="text-center jt-summary">
                          互联网 · 科技 · 创业领域活跃用户
                        </div>
                        <div class="text-right">
                          <button class="btn btn-success btn-xs">&nbsp;关注&nbsp;</button>
                        </div>
                      </div>
                    </td>
                    <td width="33.3%">
                      <div class="suggest-item-inner">
                        <div class="row">
                          <div class="col-md-12">
                            <a href="/people/so898" class="pull-left"><img src="http://p2.zhimg.com/0e/b5/0eb52fe6f_m.jpg" alt="" class="jt-avatar-40 img-rounded"></a>
                            <div class="pull-left jt-ml-10">
                              <a href="/people/so898" class="item-link">Bill Cheng</a>
                              <p class="text-muted">517 个回答</p>
                            </div>
                          </div>
                        </div>
                        
                        <div class="text-muted jt-details">
                          <small>是一只死掉的考拉，大家不用在意</small>
                        </div>
                        <hr class="devider hr-medium">
                        <div class="text-center jt-summary">
                          互联网 · 科技 · 创业领域活跃用户
                        </div>
                        <div class="text-right">
                          <button class="btn btn-success btn-xs">&nbsp;关注&nbsp;</button>
                        </div>
                      </div>
                    </td>
                    <td width="33.3%">
                      <div class="suggest-item-inner">
                        <div class="row">
                          <div class="col-md-12">
                            <a href="/people/so898" class="pull-left"><img src="http://p2.zhimg.com/0e/b5/0eb52fe6f_m.jpg" alt="" class="jt-avatar-40 img-rounded"></a>
                            <div class="pull-left jt-ml-10">
                              <a href="/people/so898">Bill Cheng</a>
                              <p class="text-muted">517 个回答</p>
                            </div>
                          </div>
                        </div>
                        
                        <div class="text-muted jt-details">
                          <small>是一只死掉的考拉，大家不用在意</small>
                        </div>
                        <hr class="devider hr-medium">
                        <div class="text-center jt-summary">
                          互联网 · 科技 · 创业领域活跃用户
                        </div>
                        <div class="text-right">
                          <button class="btn btn-success btn-xs">&nbsp;关注&nbsp;</button>
                        </div>
                      </div>
                    </td>
                  </tr>

                </table>
              </div>
            </div>
          </div>
          `foreach from=$arts item=art~
          <div class="row jt-mt-20">
            <div class="col-md-12 clearfix">
     
                <div class="pull-left jt-wt-40">
                  <a href="/people/so898" class="pull-left"><img src="`$art.avatar~" alt="" class="jt-avatar-40 img-rounded"></a>
                  <button type="button" class="btn btn-xs jt-mt-10 btn-info">&nbsp;&nbsp;`$art.like~&nbsp;&nbsp;</button>
                </div>
                <div class="jt-ml-48">
                  <div>
                    <div class="text-muted">
                      <a href="/people/so898" class="text-muted"><small>`$art.user_name~</small></a>*<a href="#" class="text-muted"><small>关注TA</small></a>
                      <span class="pull-right text-muted">精选内容</span>
                    </div>
                    <p><a href="#"><strong>`$art.title~</strong></a></p>
                    <p class="content-descript clearfix">
                      `if $art.imgs~
                      <img src="`$art.imgs|img~" class="content-img">
                      `/if~
                      `$art.descript~… <a href="javascript:void(0);" target="_blank" class="show-all">显示全部</a>
                      <textarea class="content hidden">`$art.content~</textarea>
                      
                    </p>
                  </div>
                  <div>
                    <a class="text-muted" href="#"><span class="glyphicon glyphicon-plus"></span>&nbsp;收藏路线</a>

                    <a class="text-muted jt-ml-10" href="#"><span class="glyphicon glyphicon-comment"></span>&nbsp;共`$art.comment~条评论</a>

                    <a class="content-handup text-muted jt-ml-10 pull-right hide" href="javascript:void(0);"><span class="glyphicon glyphicon-open"></span>&nbsp;收起</a>
                  </div>
                </div>
                <hr>
            </div>
            

          </div>
          `/foreach~
        </div>

        <div class="col-md-4">
          <ul class="nav nav-pills nav-stacked">
            <li><a href="#" class="text-muted"><span class="glyphicon glyphicon-file"></span>&nbsp;我的草稿</a></li>
            <li><a href="#" class="text-muted"><span class="glyphicon glyphicon-bookmark"></span>&nbsp;我的收藏</a></li>
            <li><a href="#" class="text-muted"><span class="glyphicon glyphicon-check"></span>&nbsp;我关注的人</a></li>
            <li><a href="#" class="text-muted"><span class="glyphicon glyphicon-tower"></span>&nbsp;邀请好友加入囧途</a></li>
          </ul>
          <hr>
          <p class="jt-pl-10"><b>你可能感兴趣的人</b></p>
          <div class="clearfix">
            <div class="pull-left">
              <a href="#">
                <img  class="jt-avatar-25" src="http://p2.zhimg.com/0e/b5/0eb52fe6f_m.jpg"/>
              </a>
            </div>
            <div class="jt-ml-45">
              <p><a href="#"><small>李双龙</small></a></p>
              <p class="text-muted">产品经理，从事教育类互联网产品研发</p>
              <p class="text-muted">他也关注 互联网 • 关注</p>
            </div>
          </div>

          <hr>
          <p class="jt-pl-10"><b>囧途提示</b></p>

          <div class="clearfix">
            <div class="jt-ml-10">
              
              <p class="text-muted">&nbsp;&nbsp;&nbsp;&nbsp;出行都是为了获得一段美好的体验，带上一副好心情traveling light,既然是traveling light,就一定要轻，带上足够的银子，几件换洗的衣服，就果断出发吧，千万别上山背石头哦。。。</p>
            </div>
            
          </div>
        </div>
      </div>


    </div>
    <!--底部-->
`include file=index/footer.phtml~