<div class="col-md-3">
	<div class="bs-sidebar hidden-print affix" role="complementary">
		<ul class="nav bs-sidenav">

			<li class="active">
				<a href="#download">管理</a>
				<ul class="nav">
					<li class="">
						<a href="`$url~/material">素材管理</a>
					</li>
					<li class="">
						<a href="`$url~/travel">游记管理</a>
					</li>
				</ul>
			</li>
			<li class="">
				<a href="#whats-included">设置</a>
			</li>
			<li class="">
				<a href="#template">基本模版</a>
			</li>
			<li class="">
				<a href="#examples">案例</a>
			</li>
			<li class="">
				<a href="#disable-responsive">禁用响应式布局</a>
			</li>
			<li>
				<a href="#migration">从2.x升级到3.0版本</a>
				<ul class="nav">
					<li>
						<a href="#migration-classes">被修改的主要class</a>
					</li>
					<li>
						<a href="#migration-new">新增class</a>
					</li>
					<li>
						<a href="#migration-dropped">被移除的class</a>
					</li>
					<li>
						<a href="#migration-notes">额外注意</a>
					</li>
				</ul>
			</li>
			<li>
				<a href="#browsers">浏览器支持</a>
			</li>
			<li>
				<a href="#third-parties">对第三方组件的支持</a>
			</li>
			<li>
				<a href="#accessibility">可访问性</a>
			</li>
			<li>
				<a href="#license-faqs">许可证FAQ</a>
			</li>
			<li>
				<a href="#customizing">定制Bootstrap</a>
			</li>

		</ul>
	</div>
</div>